### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by snaildos** [officialpiyush/modmail-plugins#17]
After waiting and getting lots of trouble with my modmail bot, I got it to work!!! YAY!! Its so cool, but maybe, as it can only backup, maybe there should be a restore option?
Idk, Something to think of, thanks for the Amazing plugin!

**Comment by whopiyush** [comment]
Yes, restore is a thing, on my local machine tho 😛, will push it asap after testing

**Comment by snaildos** [comment]
Ok thanks!!
