### ISSUE TITLE
Error with React To Contact

### ISSUE THREAD

**Issue by snaildos** [officialpiyush/modmail-plugins#20]
Sorry for creating another issue, but the react to contact is not working for me:

Converting to "id" failed for parameter "messageid".

Thats what I get, idk why?

**Comment by whopiyush** [comment]
1. Don't be sorry , you can create as many issues you want for feature request / bugs

2. Thanks for letting me know, I'll fix it asap

**Comment by snaildos** [comment]
Is it Normal that I am still having the error? No rush, just wondering if it is fixed, and if it is just me?

**Comment by whopiyush** [comment]
I'm rewriting this thing, will be fixed soon

**Comment by snaildos** [comment]
Ah ok Thanks!

**Comment by snaildos** [comment]
I can see that it has been updated, it now says, "Please give a valid message link"
the format I am using is:
?setreaction https://discordapp.com/channels/522708457963388948/563291090145247236/584547687072923652

but its still not working :-/

**Comment by whopiyush** [comment]
__It should be fixed!__

### Commits Involved during fixes

* https://github.com/officialpiyush/modmail-plugins/commit/63e2aad6557c1434adfee717c1a272853d799ffa
 * https://github.com/officialpiyush/modmail-plugins/commit/ac958cf2cc59aafbd68453397f77069f4bf3ba2b
* https://github.com/officialpiyush/modmail-plugins/commit/bcb84b8108ba35a82992b2b1b5fcd9236e2241d3
* https://github.com/officialpiyush/modmail-plugins/commit/c051da4554c547024d03ce46ec33ce8532500323
* https://github.com/officialpiyush/modmail-plugins/commit/67d086a3d98a1367f3be09ace907cdffff52553a
* https://github.com/officialpiyush/modmail-plugins/commit/4d4b35a6ef22bb88b2222209561efbeb6c425e10
* https://github.com/officialpiyush/modmail-plugins/commit/48f5803c834758aaed5c324d69795c95edd388d7
* https://github.com/officialpiyush/modmail-plugins/commit/e2effcc1546755c57a495c6735637dc9b5fcfc06
* https://github.com/officialpiyush/modmail-plugins/commit/e6e6f1aca4854358cc201bfd1c5c80867f7d838b
* https://github.com/officialpiyush/modmail-plugins/commit/bcb758b1ccf4c36215a6ce19507291e1fb031aad
* https://github.com/officialpiyush/modmail-plugins/commit/eedb8efe37bae77190bda7f3d1e758a884efd9aa
* https://github.com/officialpiyush/modmail-plugins/commit/6c4cd95e169f5a2fc33d5d691282c07014195a2a
* https://github.com/officialpiyush/modmail-plugins/commit/6f9c1e5d62ba8bd90c1a3e5bb371185986d1fea5
