### ISSUE TITLE
Announcement Suggestion: Edit existing announcement

### ISSUE THREAD

**Issue by Maxdg** [officialpiyush/modmail-plugins#46]
Currently there is no way to edit an existing announcement, you have to go through the whole start process again if you want to make a simple change.

I would suggest to create a way to edit the announcement, like ?announcement edit messageID simple/start

**Comment by piyushc0** [comment]
Noice

**Comment by whopiyush** [comment]
Thanks! Would look into it.

**Comment by whopiyush** [comment]
Closing due to #40 ( It has a better explanation, so keeping that and closing this )
