### ISSUE TITLE
Suggestion for Announcement plugin

### ISSUE THREAD

**Issue by Jees1** [officialpiyush/modmail-plugins#48]
Make it possible to set a role that has  announcement permissions.

**Comment by whopiyush** [comment]
Hi Jees!
Thanks for creating an issue. Right now the bot checks the setup Admin role. So if u wanna allow only a specific role to use it, set a role for ADMIN permission level.

Thanks!

**Comment by whopiyush** [comment]
Modmail core added core functionality to override the permissions of the command(S). You can use that now!
