### ISSUE TITLE
Moderation Bug, unmuting someone doesn't remove the entry but changes it.

### ISSUE THREAD

**Issue by Maxdg** [officialpiyush/modmail-plugins#49]
In this case we have User#1.

whenever I `--mute User#1 somereason`

it does get added to each channel as a permission per user, this is not bad. 

However, when I unmute that person, it doesn't remove the permission entry in the channels. It just changes it to Write = true. This is bad if you have channels that has permissions as false for @everyone. This way they have access to it even though everyone is blocked to write in a channel, AFAIK user permissions override @everyone.

It should
1.) Change the permission to '-' to match Everyone
or
2.) Remove the entry in the channel permissions.

**Comment by whopiyush** [comment]
Hello. As of now, I no longer maintain the moderation plugin. So this issue is unrelated now, but I may work on it in the near future. Thanks!

Closing this issue.
