### ISSUE TITLE
mention roles in embed announcement

### ISSUE THREAD

**Issue by Jees1** [officialpiyush/modmail-plugins#68]
Add the possibility to mention roles in embed announcements

**Comment by whopiyush** [comment]
It does ping the role, the only problem is with `@everyone` and `@here`, which would be covered in #69 .
![image](https://user-images.githubusercontent.com/18086566/72219272-4776e080-356a-11ea-8f18-4ed7dba5e0c1.png)

**Comment by Jees1** [comment]
I never knew that feature existed, wow thx

**Comment by whopiyush** [comment]
no worries + yw :)
