### ISSUE TITLE
Mentioning @everyone and @here

### ISSUE THREAD

**Issue by Jees1** [officialpiyush/modmail-plugins#69]
Make it so we can use everyone and here in the role part of this command`?announcement quick #channel (role) (msg)`
Ex. `?announcement quick #announcements everyone I just submitted a cool suggestion`
would post: ”@everyone I just submitted a cool suggestion”

**Comment by whopiyush** [comment]
You can add that in the plain message too but seems like a cool idea. Thanks!

**Comment by Jees1** [comment]
> You can add that in the plain message too but seems like a cool idea. Thanks!

But, I don’t want some admins to get pinged twice.

**Comment by whopiyush** [comment]
Yea lol

**Comment by whopiyush** [comment]
Fixed in https://github.com/officialpiyush/modmail-plugins/commit/91efbaacb55d3c3d1024d735e7a56ff797fdbe16 and https://github.com/officialpiyush/modmail-plugins/commit/ff58db8f07332e038a4ef3e8a516f30ff91cfbb5
