### ISSUE TITLE
[Request] Make giveaway plugin like Santa Wumpus

### ISSUE THREAD

**Issue by Shashank3736** [officialpiyush/modmail-plugins#70]
It would be g8 if you make your Giveaway plugin work like Santa wumpus bot. Like we can set all the req. for joining the giveaway.

**Comment by whopiyush** [comment]
Noice. You need a whole bot's features in a "plugin". This shall take time though :p

**Comment by Anonymyous678** [comment]
Yes this will be great if you will add it (must join guild, must have role to join giveaway)

**Comment by whopiyush** [comment]
Hi,
Sorry to say, I have 90% dropped the idea of doing this. You can use the standalone, and popular bot which gives the same features, Santa Wumpus bot

**Comment by catsarecoo** [comment]
@officialpiyush it's a great idea cmon do it, it will make all happy

**Comment by whopiyush** [comment]
@catsarecoo The main thing here is time, I don't have that time to add those features, instead I would like to focus on new plugins ( and fixing some plugins ofc ). But if anyone is willing to pay for it, I am more than happy to add those features in a *private* plugin.

PS: For private plugins, I am waiting for https://github.com/kyb3r/modmail/pull/2767 this PR to get merged, which shall allow downloading plugins from a private repository

**Comment by UniqueDuh** [comment]
Oh yea please do it

**Comment by misa-coder** [comment]
:joy: want a complete bot in plugin.

**Comment by impressiveaustin** [comment]
pls do it

**Comment by Shashank3736** [comment]
OK so i see good amount of attention here but i m a devil so i will close it ✡️

**Comment by UniqueDuh** [comment]
> OK so i see good amount of attention here but i m a devil so i will close it ✡️

Brug
