### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by misa-coder** [officialpiyush/modmail-plugins#77]
Please provide us with:

*  Details about your feature request
I would love it if there a ?tags list command is present.

**Comment by whopiyush** [comment]
Ah, gotcha, I'll have a look into it soon™

**Comment by misa-coder** [comment]
Yahh that will be gr8 I don't think it hard execute. I already coded it in js

**Comment by misa-coder** [comment]
Is there any update regarding this feature

**Comment by misa-coder** [comment]
Ok so all your modmail projects are dead

**Comment by whopiyush** [comment]
:p

**Comment by StephenDaDev** [comment]
> Ok so all your modmail projects are dead
- @misa-coder That does sum it up quite well

**Comment by Shashank3736** [comment]
> Ok so all your modmail projects are dead

Yeah
