### ISSUE TITLE
I get an error when installing the music plugin

### ISSUE THREAD

**Issue by mrhappyma** [officialpiyush/modmail-plugins#78]
![Screenshot 2020-06-07 at 9 59 24 AM](https://user-images.githubusercontent.com/55963440/83970789-9f114200-a8a5-11ea-8f8c-4c572f536136.png)

**Comment by lorenzo132** [comment]
Hey there, this music plugin will not work if you use heroku to host your modmail instance.

**Comment by mrhappyma** [comment]
> Hey there, this music plugin will not work if you use heroku to host your modmail instance.

OK... Thanks I guess.
